name: gold
services:
  postgres:
    image: 'postgres:16.6'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '127.0.0.1:5432:5432'
