name: gold
services:
  postgres:
    image: 'postgres:16.6'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
      - 'POSTGRES_USER=${DB_USERNAME}'
    ports:
      - '127.0.0.1:5432:5432'
